#define TIME                             1
#define UPPERCASE                        2
#define AVERAGE                          3
#define INCREASE                         4
#define MAXIMUM                          5
#define IS                               6
#define AMPERSAND                        7
#define PLUS                             8
#define MINUS                            9
#define TIMES                           10
#define DIVIDE                          11
#define SQRT                            12
#define UNMINUS                         13
#define POWER                           14
#define RANGE                           15
#define WRITE                           16
#define SEMICOLON                       17
#define TRACE                           18
#define IDENTIFIER                      19
#define ASSIGN                          20
#define IF                              21
#define THEN                            22
#define ENDIF                           23
#define ELSE                            24
#define ELSEIF                          25
#define FOR                             26
#define IN                              27
#define DO                              28
#define ENDDO                           29
#define NOW                             30
#define CURRENTTIME                     31
#define LPAR                            32
#define RPAR                            33
#define NUMTOKEN                        34
#define TIMETOKEN                       35
#define STRTOKEN                        36
#define NUMBER                          37
#define LIST                            38
#define NULLTOK                         39
#define TRUE                            40
#define FALSE                           41
#define LSPAR                           42
#define RSPAR                           43
#define COMMA                           44
