/* This file is automatically generated by Lemon from input grammar
** source file "grammar.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include "cjson.h"
#include "grammar.h"
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <setjmp.h>

/** start: what should be the header file */
#define DEBUG
#ifdef DEBUG
#define DEBUG_PRINT(fmt, ...) \
    fprintf(stderr, "[DEBUG] %s:%d:%s(): " fmt "\n", \
            __FILE__, __LINE__, __func__, ##__VA_ARGS__)
#else
#define DEBUG_PRINT(fmt, ...) \
    do { } while (0)
#endif

typedef struct { cJSON *cjson_ptr; } State;
typedef struct {char *value; int line;} token;

int get_token_id (char*);
const char *getValue (cJSON *token);
const char *getLine (cJSON *token);
cJSON *unary (char *fname, cJSON *a);
cJSON *binary (char *fname, cJSON *a, cJSON *b);
cJSON *ternary (char *fname, cJSON *a, cJSON *b, cJSON *c);
/** end: what should be the header file */

char *linenumber;
char *curtoken;
char *curtype;
static jmp_buf s_jumpBuffer;
#line 64 "grammar.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef READ
#define READ                            1
#define TIME                            2
#define WHERE                           3
#define UPPERCASE                       4
#define AVERAGE                         5
#define INCREASE                        6
#define MAXIMUM                         7
#define IS                              8
#define ISNULL                          9
#define ISLIST                         10
#define ISNUMBER                       11
#define ISWITHIN                       12
#define ISNOTWITHIN                    13
#define LT                             14
#define AMPERSAND                      15
#define PLUS                           16
#define MINUS                          17
#define TIMES                          18
#define DIVIDE                         19
#define SQRT                           20
#define UNMINUS                        21
#define POWER                          22
#define RANGE                          23
#define WRITE                          24
#define SEMICOLON                      25
#define TRACE                          26
#define IDENTIFIER                     27
#define ASSIGN                         28
#define IF                             29
#define THEN                           30
#define ENDIF                          31
#define ELSE                           32
#define ELSEIF                         33
#define FOR                            34
#define IN                             35
#define DO                             36
#define ENDDO                          37
#define OF                             38
#define NOW                            39
#define CURRENTTIME                    40
#define LPAR                           41
#define RPAR                           42
#define NUMTOKEN                       43
#define TIMETOKEN                      44
#define STRTOKEN                       45
#define NUMBER                         46
#define NOT                            47
#define ISNOTNUMBER                    48
#define LIST                           49
#define NULLTOK                        50
#define WITHIN                         51
#define TO                             52
#define TRUE                           53
#define FALSE                          54
#define LSPAR                          55
#define RSPAR                          56
#define COMMA                          57
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 66
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE cJSON *
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  State *state ;
#define ParseARG_PDECL , State *state 
#define ParseARG_PARAM ,state 
#define ParseARG_FETCH  State *state =yypParser->state ;
#define ParseARG_STORE yypParser->state =state ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             88
#define YYNRULE              53
#define YYNRULE_WITH_ACTION  51
#define YYNTOKEN             58
#define YY_MAX_SHIFT         87
#define YY_MIN_SHIFTREDUCE   118
#define YY_MAX_SHIFTREDUCE   170
#define YY_ERROR_ACTION      171
#define YY_ACCEPT_ACTION     172
#define YY_NO_ACTION         173
#define YY_MIN_REDUCE        174
#define YY_MAX_REDUCE        226
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (363)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   176,   27,   41,  181,   40,   38,   37,   39,  172,   36,
 /*    10 */    26,   17,   56,   48,  184,   68,   74,   15,   48,  180,
 /*    20 */    25,   28,   30,   22,   20,   18,   16,  138,   45,   14,
 /*    30 */    24,   81,  131,   14,   24,   46,   47,   49,   50,  132,
 /*    40 */   133,   31,   80,  135,  136,  137,   64,  148,   51,   65,
 /*    50 */   162,   55,   32,  163,  164,    1,  165,   27,   41,   75,
 /*    60 */    40,   38,   37,   39,  147,   78,   26,  149,  150,   11,
 /*    70 */    76,   68,   19,   15,   73,   60,   25,   28,   30,   22,
 /*    80 */    20,   18,   16,  138,   72,   14,   24,   61,  130,  166,
 /*    90 */    13,   70,   62,   69,  176,  132,  133,   31,   63,  135,
 /*   100 */   136,  137,  210,   26,   77,   59,  162,   57,   68,  163,
 /*   110 */   164,    1,   66,   58,   28,   30,   22,   20,   18,   16,
 /*   120 */    18,   16,   14,   24,   14,   24,   26,   22,   20,   18,
 /*   130 */    16,   68,   67,   14,   24,   53,   42,   28,   30,   22,
 /*   140 */    20,   18,   16,   26,   52,   14,   24,   54,   68,   21,
 /*   150 */   169,   23,   29,   44,   28,   30,   22,   20,   18,   16,
 /*   160 */    34,   26,   14,   24,   35,  123,   68,    4,    7,    5,
 /*   170 */    79,  129,   28,   30,   22,   20,   18,   16,    6,   26,
 /*   180 */    14,   24,   83,  122,   68,  127,  126,    8,  173,  173,
 /*   190 */    28,   30,   22,   20,   18,   16,   26,  173,   14,   24,
 /*   200 */   173,   68,  173,  173,  173,  173,  173,   28,   30,   22,
 /*   210 */    20,   18,   16,  173,  173,   14,   24,  173,  173,   26,
 /*   220 */   173,  173,  173,  173,   68,  173,  173,  173,   10,  173,
 /*   230 */    28,   30,   22,   20,   18,   16,  173,   26,   14,   24,
 /*   240 */   173,  173,   68,  173,  173,   12,  173,  173,   28,   30,
 /*   250 */    22,   20,   18,   16,  173,   26,   14,   24,  134,  121,
 /*   260 */    68,   71,  173,  173,  173,  173,   28,   30,   22,   20,
 /*   270 */    18,   16,  173,  173,   14,   24,  173,  173,  173,  173,
 /*   280 */   173,  173,  173,   33,  173,    9,   87,  173,    3,  173,
 /*   290 */    86,   43,    2,   84,   68,  173,  173,  173,  173,  173,
 /*   300 */    28,   30,   22,   20,   18,   16,   71,  173,   14,   24,
 /*   310 */   174,  173,   71,  173,  173,   28,   30,   22,   20,   18,
 /*   320 */    16,   71,  173,   14,   24,  173,  173,  173,   33,  173,
 /*   330 */     9,   87,  173,    3,   33,  173,    9,   87,   84,    3,
 /*   340 */   173,   82,  173,   33,   84,    9,   87,  173,    3,  173,
 /*   350 */    85,  173,  173,   84,   30,   22,   20,   18,   16,  173,
 /*   360 */   173,   14,   24,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    60,    1,    2,   63,    4,    5,    6,    7,   58,   59,
 /*    10 */     3,   64,   61,   61,   62,    8,   65,   17,   61,   62,
 /*    20 */    20,   14,   15,   16,   17,   18,   19,   27,   61,   22,
 /*    30 */    23,   27,   25,   22,   23,   61,   61,   61,   61,   39,
 /*    40 */    40,   41,   38,   43,   44,   45,   61,   46,   61,   61,
 /*    50 */    50,   61,   51,   53,   54,   55,   56,    1,    2,   61,
 /*    60 */     4,    5,    6,    7,   46,   47,    3,   49,   50,   51,
 /*    70 */    61,    8,   64,   17,   61,   61,   20,   14,   15,   16,
 /*    80 */    17,   18,   19,   27,   61,   22,   23,   61,   25,   56,
 /*    90 */    57,   61,   61,   61,   60,   39,   40,   41,   61,   43,
 /*   100 */    44,   45,   61,    3,   61,   61,   50,   61,    8,   53,
 /*   110 */    54,   55,   61,   61,   14,   15,   16,   17,   18,   19,
 /*   120 */    18,   19,   22,   23,   22,   23,    3,   16,   17,   18,
 /*   130 */    19,    8,   61,   22,   23,   61,   36,   14,   15,   16,
 /*   140 */    17,   18,   19,    3,   61,   22,   23,   61,    8,   64,
 /*   150 */    38,   64,   64,   30,   14,   15,   16,   17,   18,   19,
 /*   160 */    59,    3,   22,   23,   59,   25,    8,   59,   35,   28,
 /*   170 */    27,   25,   14,   15,   16,   17,   18,   19,   28,    3,
 /*   180 */    22,   23,   27,   25,    8,   25,   25,   28,   66,   66,
 /*   190 */    14,   15,   16,   17,   18,   19,    3,   66,   22,   23,
 /*   200 */    66,    8,   66,   66,   66,   66,   66,   14,   15,   16,
 /*   210 */    17,   18,   19,   66,   66,   22,   23,   66,   66,    3,
 /*   220 */    66,   66,   66,   66,    8,   66,   66,   66,   52,   66,
 /*   230 */    14,   15,   16,   17,   18,   19,   66,    3,   22,   23,
 /*   240 */    66,   66,    8,   66,   66,   52,   66,   66,   14,   15,
 /*   250 */    16,   17,   18,   19,   66,    3,   22,   23,   42,   25,
 /*   260 */     8,    2,   66,   66,   66,   66,   14,   15,   16,   17,
 /*   270 */    18,   19,   66,   66,   22,   23,   66,   66,   66,   66,
 /*   280 */    66,   66,   66,   24,   66,   26,   27,   66,   29,   66,
 /*   290 */    31,   32,   33,   34,    8,   66,   66,   66,   66,   66,
 /*   300 */    14,   15,   16,   17,   18,   19,    2,   66,   22,   23,
 /*   310 */     0,   66,    2,   66,   66,   14,   15,   16,   17,   18,
 /*   320 */    19,    2,   66,   22,   23,   66,   66,   66,   24,   66,
 /*   330 */    26,   27,   66,   29,   24,   66,   26,   27,   34,   29,
 /*   340 */    66,   37,   66,   24,   34,   26,   27,   66,   29,   66,
 /*   350 */    31,   66,   66,   34,   15,   16,   17,   18,   19,   66,
 /*   360 */    66,   22,   23,   66,   66,   66,   66,   66,   66,   66,
 /*   370 */    66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
 /*   380 */    66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
 /*   390 */    66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
 /*   400 */    66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
 /*   410 */    66,   66,   66,   58,   58,   58,   58,   58,   58,   58,
 /*   420 */    58,
};
#define YY_SHIFT_COUNT    (87)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (339)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   363,    0,   56,   56,  259,   56,   56,   56,   56,   56,
 /*    10 */    56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
 /*    20 */    56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
 /*    30 */    56,   56,   56,   56,  304,  319,  310,  112,  112,  112,
 /*    40 */   112,  112,  363,  363,  363,    7,   63,  100,  123,  140,
 /*    50 */   158,  176,  193,  216,  234,  252,  252,  252,  252,  286,
 /*    60 */   286,  286,  286,  286,  301,  301,  339,  111,   18,  102,
 /*    70 */   102,    4,   11,   11,   33,   11,   11,   11,    1,  141,
 /*    80 */   143,  150,  146,  133,  155,  160,  161,  159,
};
#define YY_REDUCE_COUNT (44)
#define YY_REDUCE_MIN   (-60)
#define YY_REDUCE_MAX   (108)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -50,  -49,  -48,  -43,  -60,  -33,  -26,  -25,  -24,  -23,
 /*    10 */   -15,  -13,  -12,  -10,   -2,    9,   13,   14,   23,   26,
 /*    20 */    30,   31,   32,   37,   41,   43,   44,   46,   51,   52,
 /*    30 */    71,   74,   83,   86,   34,   34,   34,  -53,    8,   85,
 /*    40 */    87,   88,  101,  105,  108,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   175,  171,  171,  171,  171,  171,  171,  171,  171,  171,
 /*    10 */   171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
 /*    20 */   171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
 /*    30 */   171,  171,  171,  171,  171,  171,  171,  226,  226,  226,
 /*    40 */   226,  226,  175,  175,  175,  171,  171,  171,  171,  171,
 /*    50 */   171,  171,  171,  171,  171,  224,  223,  196,  195,  209,
 /*    60 */   201,  200,  199,  198,  217,  216,  208,  207,  171,  211,
 /*    70 */   212,  171,  213,  214,  171,  215,  202,  197,  171,  171,
 /*    80 */   171,  171,  171,  171,  171,  171,  171,  171,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "READ",
  /*    2 */ "TIME",
  /*    3 */ "WHERE",
  /*    4 */ "UPPERCASE",
  /*    5 */ "AVERAGE",
  /*    6 */ "INCREASE",
  /*    7 */ "MAXIMUM",
  /*    8 */ "IS",
  /*    9 */ "ISNULL",
  /*   10 */ "ISLIST",
  /*   11 */ "ISNUMBER",
  /*   12 */ "ISWITHIN",
  /*   13 */ "ISNOTWITHIN",
  /*   14 */ "LT",
  /*   15 */ "AMPERSAND",
  /*   16 */ "PLUS",
  /*   17 */ "MINUS",
  /*   18 */ "TIMES",
  /*   19 */ "DIVIDE",
  /*   20 */ "SQRT",
  /*   21 */ "UNMINUS",
  /*   22 */ "POWER",
  /*   23 */ "RANGE",
  /*   24 */ "WRITE",
  /*   25 */ "SEMICOLON",
  /*   26 */ "TRACE",
  /*   27 */ "IDENTIFIER",
  /*   28 */ "ASSIGN",
  /*   29 */ "IF",
  /*   30 */ "THEN",
  /*   31 */ "ENDIF",
  /*   32 */ "ELSE",
  /*   33 */ "ELSEIF",
  /*   34 */ "FOR",
  /*   35 */ "IN",
  /*   36 */ "DO",
  /*   37 */ "ENDDO",
  /*   38 */ "OF",
  /*   39 */ "NOW",
  /*   40 */ "CURRENTTIME",
  /*   41 */ "LPAR",
  /*   42 */ "RPAR",
  /*   43 */ "NUMTOKEN",
  /*   44 */ "TIMETOKEN",
  /*   45 */ "STRTOKEN",
  /*   46 */ "NUMBER",
  /*   47 */ "NOT",
  /*   48 */ "ISNOTNUMBER",
  /*   49 */ "LIST",
  /*   50 */ "NULLTOK",
  /*   51 */ "WITHIN",
  /*   52 */ "TO",
  /*   53 */ "TRUE",
  /*   54 */ "FALSE",
  /*   55 */ "LSPAR",
  /*   56 */ "RSPAR",
  /*   57 */ "COMMA",
  /*   58 */ "code",
  /*   59 */ "statementblock",
  /*   60 */ "statement",
  /*   61 */ "ex",
  /*   62 */ "if_then_else",
  /*   63 */ "elseif",
  /*   64 */ "optional_of",
  /*   65 */ "exlist",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "code ::= statementblock",
 /*   1 */ "statementblock ::=",
 /*   2 */ "statementblock ::= statementblock statement",
 /*   3 */ "statement ::= WRITE ex SEMICOLON",
 /*   4 */ "statement ::= TRACE ex SEMICOLON",
 /*   5 */ "statement ::= IDENTIFIER ASSIGN ex SEMICOLON",
 /*   6 */ "statement ::= IF if_then_else",
 /*   7 */ "if_then_else ::= ex THEN statementblock elseif",
 /*   8 */ "elseif ::= ENDIF SEMICOLON",
 /*   9 */ "elseif ::= ELSE statementblock ENDIF SEMICOLON",
 /*  10 */ "elseif ::= ELSEIF if_then_else",
 /*  11 */ "statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON",
 /*  12 */ "statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON",
 /*  13 */ "statement ::= TIME OF IDENTIFIER ASSIGN ex SEMICOLON",
 /*  14 */ "ex ::= NOW",
 /*  15 */ "ex ::= CURRENTTIME",
 /*  16 */ "ex ::= LPAR ex RPAR",
 /*  17 */ "ex ::= NUMTOKEN",
 /*  18 */ "ex ::= TIMETOKEN",
 /*  19 */ "ex ::= STRTOKEN",
 /*  20 */ "ex ::= IDENTIFIER",
 /*  21 */ "ex ::= TIME optional_of ex",
 /*  22 */ "ex ::= READ ex",
 /*  23 */ "ex ::= SQRT ex",
 /*  24 */ "ex ::= UPPERCASE optional_of ex",
 /*  25 */ "ex ::= MAXIMUM optional_of ex",
 /*  26 */ "ex ::= AVERAGE optional_of ex",
 /*  27 */ "ex ::= INCREASE optional_of ex",
 /*  28 */ "ex ::= MINUS ex",
 /*  29 */ "ex ::= ex IS NUMBER",
 /*  30 */ "ex ::= ex IS NOT NUMBER",
 /*  31 */ "ex ::= ex IS LIST",
 /*  32 */ "ex ::= ex IS NULLTOK",
 /*  33 */ "ex ::= ex AMPERSAND ex",
 /*  34 */ "ex ::= ex LT ex",
 /*  35 */ "ex ::= ex WHERE ex",
 /*  36 */ "ex ::= ex RANGE ex",
 /*  37 */ "ex ::= ex PLUS ex",
 /*  38 */ "ex ::= ex MINUS ex",
 /*  39 */ "ex ::= ex TIMES ex",
 /*  40 */ "ex ::= ex DIVIDE ex",
 /*  41 */ "ex ::= ex POWER ex",
 /*  42 */ "ex ::= ex IS NOT WITHIN ex TO ex",
 /*  43 */ "ex ::= ex IS WITHIN ex TO ex",
 /*  44 */ "ex ::= NULLTOK",
 /*  45 */ "ex ::= TRUE",
 /*  46 */ "ex ::= FALSE",
 /*  47 */ "ex ::= LSPAR RSPAR",
 /*  48 */ "ex ::= LSPAR exlist RSPAR",
 /*  49 */ "exlist ::= ex",
 /*  50 */ "exlist ::= exlist COMMA ex",
 /*  51 */ "optional_of ::= OF",
 /*  52 */ "optional_of ::=",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    58,  /* (0) code ::= statementblock */
    59,  /* (1) statementblock ::= */
    59,  /* (2) statementblock ::= statementblock statement */
    60,  /* (3) statement ::= WRITE ex SEMICOLON */
    60,  /* (4) statement ::= TRACE ex SEMICOLON */
    60,  /* (5) statement ::= IDENTIFIER ASSIGN ex SEMICOLON */
    60,  /* (6) statement ::= IF if_then_else */
    62,  /* (7) if_then_else ::= ex THEN statementblock elseif */
    63,  /* (8) elseif ::= ENDIF SEMICOLON */
    63,  /* (9) elseif ::= ELSE statementblock ENDIF SEMICOLON */
    63,  /* (10) elseif ::= ELSEIF if_then_else */
    60,  /* (11) statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON */
    60,  /* (12) statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON */
    60,  /* (13) statement ::= TIME OF IDENTIFIER ASSIGN ex SEMICOLON */
    61,  /* (14) ex ::= NOW */
    61,  /* (15) ex ::= CURRENTTIME */
    61,  /* (16) ex ::= LPAR ex RPAR */
    61,  /* (17) ex ::= NUMTOKEN */
    61,  /* (18) ex ::= TIMETOKEN */
    61,  /* (19) ex ::= STRTOKEN */
    61,  /* (20) ex ::= IDENTIFIER */
    61,  /* (21) ex ::= TIME optional_of ex */
    61,  /* (22) ex ::= READ ex */
    61,  /* (23) ex ::= SQRT ex */
    61,  /* (24) ex ::= UPPERCASE optional_of ex */
    61,  /* (25) ex ::= MAXIMUM optional_of ex */
    61,  /* (26) ex ::= AVERAGE optional_of ex */
    61,  /* (27) ex ::= INCREASE optional_of ex */
    61,  /* (28) ex ::= MINUS ex */
    61,  /* (29) ex ::= ex IS NUMBER */
    61,  /* (30) ex ::= ex IS NOT NUMBER */
    61,  /* (31) ex ::= ex IS LIST */
    61,  /* (32) ex ::= ex IS NULLTOK */
    61,  /* (33) ex ::= ex AMPERSAND ex */
    61,  /* (34) ex ::= ex LT ex */
    61,  /* (35) ex ::= ex WHERE ex */
    61,  /* (36) ex ::= ex RANGE ex */
    61,  /* (37) ex ::= ex PLUS ex */
    61,  /* (38) ex ::= ex MINUS ex */
    61,  /* (39) ex ::= ex TIMES ex */
    61,  /* (40) ex ::= ex DIVIDE ex */
    61,  /* (41) ex ::= ex POWER ex */
    61,  /* (42) ex ::= ex IS NOT WITHIN ex TO ex */
    61,  /* (43) ex ::= ex IS WITHIN ex TO ex */
    61,  /* (44) ex ::= NULLTOK */
    61,  /* (45) ex ::= TRUE */
    61,  /* (46) ex ::= FALSE */
    61,  /* (47) ex ::= LSPAR RSPAR */
    61,  /* (48) ex ::= LSPAR exlist RSPAR */
    65,  /* (49) exlist ::= ex */
    65,  /* (50) exlist ::= exlist COMMA ex */
    64,  /* (51) optional_of ::= OF */
    64,  /* (52) optional_of ::= */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) code ::= statementblock */
    0,  /* (1) statementblock ::= */
   -2,  /* (2) statementblock ::= statementblock statement */
   -3,  /* (3) statement ::= WRITE ex SEMICOLON */
   -3,  /* (4) statement ::= TRACE ex SEMICOLON */
   -4,  /* (5) statement ::= IDENTIFIER ASSIGN ex SEMICOLON */
   -2,  /* (6) statement ::= IF if_then_else */
   -4,  /* (7) if_then_else ::= ex THEN statementblock elseif */
   -2,  /* (8) elseif ::= ENDIF SEMICOLON */
   -4,  /* (9) elseif ::= ELSE statementblock ENDIF SEMICOLON */
   -2,  /* (10) elseif ::= ELSEIF if_then_else */
   -8,  /* (11) statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON */
   -5,  /* (12) statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON */
   -6,  /* (13) statement ::= TIME OF IDENTIFIER ASSIGN ex SEMICOLON */
   -1,  /* (14) ex ::= NOW */
   -1,  /* (15) ex ::= CURRENTTIME */
   -3,  /* (16) ex ::= LPAR ex RPAR */
   -1,  /* (17) ex ::= NUMTOKEN */
   -1,  /* (18) ex ::= TIMETOKEN */
   -1,  /* (19) ex ::= STRTOKEN */
   -1,  /* (20) ex ::= IDENTIFIER */
   -3,  /* (21) ex ::= TIME optional_of ex */
   -2,  /* (22) ex ::= READ ex */
   -2,  /* (23) ex ::= SQRT ex */
   -3,  /* (24) ex ::= UPPERCASE optional_of ex */
   -3,  /* (25) ex ::= MAXIMUM optional_of ex */
   -3,  /* (26) ex ::= AVERAGE optional_of ex */
   -3,  /* (27) ex ::= INCREASE optional_of ex */
   -2,  /* (28) ex ::= MINUS ex */
   -3,  /* (29) ex ::= ex IS NUMBER */
   -4,  /* (30) ex ::= ex IS NOT NUMBER */
   -3,  /* (31) ex ::= ex IS LIST */
   -3,  /* (32) ex ::= ex IS NULLTOK */
   -3,  /* (33) ex ::= ex AMPERSAND ex */
   -3,  /* (34) ex ::= ex LT ex */
   -3,  /* (35) ex ::= ex WHERE ex */
   -3,  /* (36) ex ::= ex RANGE ex */
   -3,  /* (37) ex ::= ex PLUS ex */
   -3,  /* (38) ex ::= ex MINUS ex */
   -3,  /* (39) ex ::= ex TIMES ex */
   -3,  /* (40) ex ::= ex DIVIDE ex */
   -3,  /* (41) ex ::= ex POWER ex */
   -7,  /* (42) ex ::= ex IS NOT WITHIN ex TO ex */
   -6,  /* (43) ex ::= ex IS WITHIN ex TO ex */
   -1,  /* (44) ex ::= NULLTOK */
   -1,  /* (45) ex ::= TRUE */
   -1,  /* (46) ex ::= FALSE */
   -2,  /* (47) ex ::= LSPAR RSPAR */
   -3,  /* (48) ex ::= LSPAR exlist RSPAR */
   -1,  /* (49) exlist ::= ex */
   -3,  /* (50) exlist ::= exlist COMMA ex */
   -1,  /* (51) optional_of ::= OF */
    0,  /* (52) optional_of ::= */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* code ::= statementblock */
#line 262 "grammar.y"
{
    state->cjson_ptr = yymsp[0].minor.yy0;
}
#line 1232 "grammar.c"
        break;
      case 1: /* statementblock ::= */
#line 271 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "STATEMENTBLOCK");
	cJSON *arg = cJSON_CreateArray();
	cJSON_AddItemToObject(res, "statements", arg);
	yymsp[1].minor.yy0 = res;
}
#line 1243 "grammar.c"
        break;
      case 2: /* statementblock ::= statementblock statement */
#line 280 "grammar.y"
{
	cJSON_AddItemToArray(cJSON_GetObjectItem ( yymsp[-1].minor.yy0, "statements"), yymsp[0].minor.yy0);
	yylhsminor.yy0 = yymsp[-1].minor.yy0;
}
#line 1251 "grammar.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* statement ::= WRITE ex SEMICOLON */
#line 290 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "WRITE");
	cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
	yymsp[-2].minor.yy0 = res;
}
#line 1262 "grammar.c"
        break;
      case 4: /* statement ::= TRACE ex SEMICOLON */
#line 298 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "TRACE");
    cJSON_AddStringToObject(res, "line", getLine(yymsp[-2].minor.yy0));
    cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
    yylhsminor.yy0 = res;
}
#line 1273 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 5: /* statement ::= IDENTIFIER ASSIGN ex SEMICOLON */
#line 311 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "ASSIGN");
	cJSON_AddStringToObject(res, "ident", getValue(yymsp[-3].minor.yy0));
	cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
	yylhsminor.yy0 = res;
}
#line 1285 "grammar.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 6: /* statement ::= IF if_then_else */
      case 10: /* elseif ::= ELSEIF if_then_else */ yytestcase(yyruleno==10);
#line 321 "grammar.y"
{yymsp[-1].minor.yy0 = yymsp[0].minor.yy0;}
#line 1292 "grammar.c"
        break;
      case 7: /* if_then_else ::= ex THEN statementblock elseif */
#line 324 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "IF");
    cJSON_AddItemToObject(res, "condition", yymsp[-3].minor.yy0);
    cJSON_AddItemToObject(res, "thenbranch", (yymsp[-1].minor.yy0));
    cJSON_AddItemToObject(res, "elsebranch", (yymsp[0].minor.yy0));
    yylhsminor.yy0 = res;
}
#line 1304 "grammar.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 8: /* elseif ::= ENDIF SEMICOLON */
#line 335 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "STATEMENTBLOCK");
    cJSON *arg = cJSON_CreateArray();
    cJSON_AddItemToObject(res, "statements", arg);
    yymsp[-1].minor.yy0 = res;
}
#line 1316 "grammar.c"
        break;
      case 9: /* elseif ::= ELSE statementblock ENDIF SEMICOLON */
#line 344 "grammar.y"
{yymsp[-3].minor.yy0 = yymsp[-2].minor.yy0;}
#line 1321 "grammar.c"
        break;
      case 11: /* statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON */
#line 351 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "FOR");
    cJSON_AddStringToObject(res, "varname", getValue(yymsp[-6].minor.yy0));
    cJSON_AddItemToObject(res, "expression", yymsp[-4].minor.yy0);
    cJSON_AddItemToObject(res, "statements", yymsp[-2].minor.yy0);
    yymsp[-7].minor.yy0 = res;
}
#line 1333 "grammar.c"
        break;
      case 12: /* statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON */
#line 362 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "TIMEASSIGN");
	cJSON_AddStringToObject(res, "ident", getValue(yymsp[-3].minor.yy0));
	cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
	yymsp[-4].minor.yy0 = res;
}
#line 1344 "grammar.c"
        break;
      case 13: /* statement ::= TIME OF IDENTIFIER ASSIGN ex SEMICOLON */
#line 372 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "TIMEASSIGN");
	cJSON_AddStringToObject(res, "ident", getValue(yymsp[-3].minor.yy0));
	cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
	yymsp[-5].minor.yy0 = res;
}
#line 1355 "grammar.c"
        break;
      case 14: /* ex ::= NOW */
#line 381 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "NOW");
	yymsp[0].minor.yy0 = res;
}
#line 1364 "grammar.c"
        break;
      case 15: /* ex ::= CURRENTTIME */
#line 388 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "CURRENTTIME");
	yymsp[0].minor.yy0 = res;
}
#line 1373 "grammar.c"
        break;
      case 16: /* ex ::= LPAR ex RPAR */
#line 395 "grammar.y"
{
	yymsp[-2].minor.yy0 = yymsp[-1].minor.yy0;
}
#line 1380 "grammar.c"
        break;
      case 17: /* ex ::= NUMTOKEN */
#line 401 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "NUMTOKEN");
	cJSON_AddStringToObject(res, "value", getValue(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1390 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 18: /* ex ::= TIMETOKEN */
#line 409 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "TIMETOKEN");
	cJSON_AddStringToObject(res, "value", getValue(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1401 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 19: /* ex ::= STRTOKEN */
#line 418 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "STRTOKEN");
	cJSON_AddStringToObject(res, "value", getValue(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1412 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 20: /* ex ::= IDENTIFIER */
#line 427 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "VARIABLE");
	cJSON_AddStringToObject(res, "name", getValue(yymsp[0].minor.yy0));
	cJSON_AddStringToObject(res, "line", getLine(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1424 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 21: /* ex ::= TIME optional_of ex */
#line 439 "grammar.y"
{ yymsp[-2].minor.yy0 = unary("TIME", yymsp[0].minor.yy0); }
#line 1430 "grammar.c"
        break;
      case 22: /* ex ::= READ ex */
#line 442 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("READ", yymsp[0].minor.yy0); }
#line 1435 "grammar.c"
        break;
      case 23: /* ex ::= SQRT ex */
#line 445 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("SQRT", yymsp[0].minor.yy0); }
#line 1440 "grammar.c"
        break;
      case 24: /* ex ::= UPPERCASE optional_of ex */
#line 448 "grammar.y"
{ yymsp[-2].minor.yy0 = unary("UPPERCASE", yymsp[0].minor.yy0); }
#line 1445 "grammar.c"
        break;
      case 25: /* ex ::= MAXIMUM optional_of ex */
#line 451 "grammar.y"
{ yymsp[-2].minor.yy0 = unary("MAXIMUM", yymsp[0].minor.yy0); }
#line 1450 "grammar.c"
        break;
      case 26: /* ex ::= AVERAGE optional_of ex */
#line 454 "grammar.y"
{ yymsp[-2].minor.yy0 = unary("AVERAGE", yymsp[0].minor.yy0); }
#line 1455 "grammar.c"
        break;
      case 27: /* ex ::= INCREASE optional_of ex */
#line 457 "grammar.y"
{ yymsp[-2].minor.yy0 = unary("INCREASE", yymsp[0].minor.yy0); }
#line 1460 "grammar.c"
        break;
      case 28: /* ex ::= MINUS ex */
#line 460 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("UNMINUS", yymsp[0].minor.yy0); }
#line 1465 "grammar.c"
        break;
      case 29: /* ex ::= ex IS NUMBER */
#line 463 "grammar.y"
{ yylhsminor.yy0 = unary("ISNUMBER", yymsp[-2].minor.yy0); }
#line 1470 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 30: /* ex ::= ex IS NOT NUMBER */
#line 466 "grammar.y"
{ yylhsminor.yy0 = unary("ISNOTNUMBER", yymsp[-3].minor.yy0); }
#line 1476 "grammar.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 31: /* ex ::= ex IS LIST */
#line 469 "grammar.y"
{ yylhsminor.yy0 = unary("ISLIST", yymsp[-2].minor.yy0); }
#line 1482 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 32: /* ex ::= ex IS NULLTOK */
#line 472 "grammar.y"
{ yylhsminor.yy0 = unary("ISNULL", yymsp[-2].minor.yy0); }
#line 1488 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 33: /* ex ::= ex AMPERSAND ex */
#line 475 "grammar.y"
{yylhsminor.yy0 = binary ("AMPERSAND", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1494 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 34: /* ex ::= ex LT ex */
#line 478 "grammar.y"
{yylhsminor.yy0 = binary ("LT", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1500 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 35: /* ex ::= ex WHERE ex */
#line 481 "grammar.y"
{yylhsminor.yy0 = binary ("WHERE", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1506 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 36: /* ex ::= ex RANGE ex */
#line 484 "grammar.y"
{yylhsminor.yy0 = binary ("RANGE", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1512 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 37: /* ex ::= ex PLUS ex */
#line 487 "grammar.y"
{yylhsminor.yy0 = binary ("PLUS", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1518 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 38: /* ex ::= ex MINUS ex */
#line 490 "grammar.y"
{yylhsminor.yy0 = binary ("MINUS", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1524 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 39: /* ex ::= ex TIMES ex */
#line 493 "grammar.y"
{yylhsminor.yy0 = binary ("TIMES", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1530 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 40: /* ex ::= ex DIVIDE ex */
#line 496 "grammar.y"
{yylhsminor.yy0 = binary ("DIVIDE", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1536 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 41: /* ex ::= ex POWER ex */
#line 499 "grammar.y"
{yylhsminor.yy0 = binary ("POWER", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1542 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 42: /* ex ::= ex IS NOT WITHIN ex TO ex */
#line 502 "grammar.y"
{yylhsminor.yy0 = ternary ("ISNOTWITHIN", yymsp[-6].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1548 "grammar.c"
  yymsp[-6].minor.yy0 = yylhsminor.yy0;
        break;
      case 43: /* ex ::= ex IS WITHIN ex TO ex */
#line 505 "grammar.y"
{yylhsminor.yy0 = ternary ("ISWITHIN", yymsp[-5].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1554 "grammar.c"
  yymsp[-5].minor.yy0 = yylhsminor.yy0;
        break;
      case 44: /* ex ::= NULLTOK */
#line 508 "grammar.y"
{
cJSON *res = cJSON_CreateObject();
cJSON_AddStringToObject(res, "type", "NULL");
yymsp[0].minor.yy0 = res;
}
#line 1564 "grammar.c"
        break;
      case 45: /* ex ::= TRUE */
#line 515 "grammar.y"
{
 	cJSON *res = cJSON_CreateObject();
 	cJSON_AddStringToObject(res, "type", "TRUE");
 	yymsp[0].minor.yy0 = res;
}
#line 1573 "grammar.c"
        break;
      case 46: /* ex ::= FALSE */
#line 522 "grammar.y"
{
 	cJSON *res = cJSON_CreateObject();
 	cJSON_AddStringToObject(res, "type", "FALSE");
 	yymsp[0].minor.yy0 = res;
}
#line 1582 "grammar.c"
        break;
      case 47: /* ex ::= LSPAR RSPAR */
#line 529 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "EMPTYLIST");
    yymsp[-1].minor.yy0 = res;
}
#line 1591 "grammar.c"
        break;
      case 48: /* ex ::= LSPAR exlist RSPAR */
#line 537 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "LIST");
    cJSON_AddItemToObject(res, "items", yymsp[-1].minor.yy0);
    yymsp[-2].minor.yy0 = res;
}
#line 1601 "grammar.c"
        break;
      case 49: /* exlist ::= ex */
#line 545 "grammar.y"
{
    cJSON *arg = cJSON_CreateArray();
    cJSON_AddItemToArray(arg, yymsp[0].minor.yy0);
    yylhsminor.yy0 = arg;
}
#line 1610 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 50: /* exlist ::= exlist COMMA ex */
#line 552 "grammar.y"
{
    cJSON_AddItemToArray(yymsp[-2].minor.yy0,yymsp[0].minor.yy0);
    yylhsminor.yy0 = yymsp[-2].minor.yy0;
}
#line 1619 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      default:
      /* (51) optional_of ::= OF */ yytestcase(yyruleno==51);
      /* (52) optional_of ::= */ yytestcase(yyruleno==52);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 228 "grammar.y"

    longjmp(s_jumpBuffer, 1);
#line 1687 "grammar.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
#line 39 "grammar.y"


token* create_token (char *value, int line) {
	token *t = (token*) malloc (sizeof (token));
	t->value = strdup (value);
	t->line = line;
	return t;
}

const char * getValue (cJSON* token) {
	return cJSON_GetObjectItem (token, "value")->valuestring;
}


const char * getLine (cJSON* token) {
	return cJSON_GetObjectItem (token, "line")->valuestring;
}


const char *parse_to_string(const char *input) {
	int jmp_val = setjmp(s_jumpBuffer);
	if (jmp_val != 0) {
        size_t buf_size = 256;
        char buf[buf_size];
        int n;
        if (jmp_val == 1) {
            n = snprintf(
            buf,
            buf_size,
            "{\"error\" : true, \"message\": \"Syntax Error: Compiler reports unexpected token \\\"%s\\\" of type \\\"%s\\\" in line %s\"}\n",
            curtoken, curtype, linenumber
        );
        } else if (jmp_val == 2) {
        	n = snprintf (buf, buf_size, "{\"error\" : true, \"message\": \"UNKNOWN TOKEN TYPE %s\"}\n", curtoken);
        } else {
        	n = snprintf (buf, buf_size, "{\"error\" : true, \"message\": \"Jumped here dont know why...!\"}\n");
        }

        // allocate n+1 chars (for the null terminator)
        char *res = malloc(n + 1);
        if (res == NULL) exit(1);

        // copy exactly n chars + '\0'
        memcpy(res, buf, n + 1);

        return res;
	} else {
	    cJSON *root = cJSON_Parse(input);
        State state;

	    if (!root) {
	    	printf("JSON invalid\n");
	    	exit(0);
	    }

	    void* pParser = ParseAlloc (malloc);
	    int num = cJSON_GetArraySize (root);

	    for (int i = 0; i < num; i++ ) {

	    	// Knoten im Token-Stream auslesen
	    	cJSON *node = cJSON_GetArrayItem(root,i);

	    	char *line = cJSON_GetArrayItem(node,0)->valuestring;
	    	char *type = cJSON_GetArrayItem(node,1)->valuestring;
	    	char *value = cJSON_GetArrayItem(node,2)->valuestring;

	    	cJSON *tok = cJSON_CreateObject();
	    	cJSON_AddStringToObject(tok, "value", value);
	    	cJSON_AddStringToObject(tok, "line", line);

	    	linenumber = line;
	    	curtoken = value;
	    	curtype = type;
	    	// THE und Kommentare werden ueberlesen
	    	if (strcmp(type, "THE") == 0) continue;
	    	if (strcmp(type, "COMMENT") == 0) continue;
	    	if (strcmp(type, "MCOMMENT") == 0) continue;

	    	int tokenid = get_token_id (type);
	    	Parse (pParser, tokenid, tok, &state);

	    }
	    Parse (pParser, 0, 0, &state);
        ParseFree(pParser, free );
        return cJSON_Print(state.cjson_ptr);
	}
}




///////////////////////
///////////////////////
// TOKENS
///////////////////////
///////////////////////

int get_token_id (char *token) {
	if (strcmp(token, "IS") == 0) return IS;
	if (strcmp(token, "SQRT") == 0) return SQRT;
	if (strcmp(token, "NOT") == 0) return NOT;
	if (strcmp(token, "AMPERSAND") == 0) return AMPERSAND;
	if (strcmp(token, "OF") == 0) return OF;
	if (strcmp(token, "LT") == 0) return LT;
	if (strcmp(token, "ASSIGN") == 0) return ASSIGN;
	if (strcmp(token, "COMMA") == 0) return COMMA;
	if (strcmp(token, "DIVIDE") == 0) return DIVIDE;
	if (strcmp(token, "IDENTIFIER") == 0) return IDENTIFIER;
	if (strcmp(token, "LIST") == 0) return LIST;
	if (strcmp(token, "LPAR") == 0) return LPAR;
	if (strcmp(token, "LSPAR") == 0) return LSPAR;
	if (strcmp(token, "MINUS") == 0) return MINUS;
	if (strcmp(token, "NULL") == 0) return NULLTOK;
	if (strcmp(token, "NUMTOKEN") == 0) return NUMTOKEN;
	if (strcmp(token, "NUMBER") == 0) return NUMBER;
	if (strcmp(token, "PLUS") == 0) return PLUS;
	if (strcmp(token, "POWER") == 0) return POWER;
	if (strcmp(token, "WITHIN") == 0) return WITHIN;
	if (strcmp(token, "TO") == 0) return TO;
	if (strcmp(token, "RPAR") == 0) return RPAR;
	if (strcmp(token, "RSPAR") == 0) return RSPAR;
	if (strcmp(token, "SEMICOLON") == 0) return SEMICOLON;
	if (strcmp(token, "STRTOKEN") == 0) return STRTOKEN;
	if (strcmp(token, "TIME") == 0) return TIME;
	if (strcmp(token, "TIMES") == 0) return TIMES;
	if (strcmp(token, "TIMETOKEN") == 0) return TIMETOKEN;
	if (strcmp(token, "TRACE") == 0) return TRACE;
	if (strcmp(token, "WRITE") == 0) return WRITE;
 	if (strcmp(token, "AVERAGE") == 0) return AVERAGE;
 	if (strcmp(token, "CURRENTTIME") == 0) return CURRENTTIME;
 	if (strcmp(token, "DO") == 0) return DO;
 	if (strcmp(token, "ELSE") == 0) return ELSE;
 	if (strcmp(token, "ENDDO") == 0) return ENDDO;
 	if (strcmp(token, "ENDIF") == 0) return ENDIF;
 	if (strcmp(token, "FALSE") == 0) return FALSE;
 	if (strcmp(token, "FOR") == 0) return FOR;
 	if (strcmp(token, "IF") == 0) return IF;
 	if (strcmp(token, "IN") == 0) return IN;
 	if (strcmp(token, "INCREASE") == 0) return INCREASE;
 	if (strcmp(token, "READ") == 0) return READ;
 	if (strcmp(token, "MAXIMUM") == 0) return MAXIMUM;
 	if (strcmp(token, "NOW") == 0) return NOW;
 	if (strcmp(token, "RANGE") == 0) return RANGE;
 	if (strcmp(token, "THEN") == 0) return THEN;
 	if (strcmp(token, "TRUE") == 0) return TRUE;
 	if (strcmp(token, "UPPERCASE") == 0) return UPPERCASE;
	if (strcmp(token, "WHERE") == 0) return WHERE;
    curtoken = token;
    longjmp(s_jumpBuffer, 2);
}



cJSON* unary (char* fname, cJSON* a)
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", fname);
	cJSON_AddItemToObject(res, "arg", a);
	return res;
}



cJSON* binary (char *fname, cJSON *a, cJSON *b)
{
	cJSON *res = cJSON_CreateObject();
	cJSON *arg = cJSON_CreateArray();
	cJSON_AddItemToArray(arg, a);
	cJSON_AddItemToArray(arg, b);
	cJSON_AddStringToObject(res, "type", fname);
	cJSON_AddItemToObject(res, "arg", arg);
	return res;
}

cJSON* ternary (char *fname, cJSON *a, cJSON *b, cJSON *c)
{
	cJSON *res = cJSON_CreateObject();
	cJSON *arg = cJSON_CreateArray();
	cJSON_AddItemToArray(arg, a);
	cJSON_AddItemToArray(arg, b);
	cJSON_AddItemToArray(arg, c);
	cJSON_AddStringToObject(res, "type", fname);
	cJSON_AddItemToObject(res, "arg", arg);
	return res;
}

#line 2144 "grammar.c"
