#define TIME                             1
#define UPPERCASE                        2
#define AVERAGE                          3
#define INCREASE                         4
#define MAXIMUM                          5
#define IS                               6
#define ISNULL                           7
#define ISLIST                           8
#define ISNUMBER                         9
#define ISNOTWITHIN                     10
#define AMPERSAND                       11
#define PLUS                            12
#define MINUS                           13
#define TIMES                           14
#define DIVIDE                          15
#define SQRT                            16
#define UNMINUS                         17
#define POWER                           18
#define RANGE                           19
#define WRITE                           20
#define SEMICOLON                       21
#define TRACE                           22
#define IDENTIFIER                      23
#define ASSIGN                          24
#define IF                              25
#define THEN                            26
#define ENDIF                           27
#define ELSE                            28
#define ELSEIF                          29
#define FOR                             30
#define IN                              31
#define DO                              32
#define ENDDO                           33
#define NOW                             34
#define CURRENTTIME                     35
#define LPAR                            36
#define RPAR                            37
#define NUMTOKEN                        38
#define TIMETOKEN                       39
#define STRTOKEN                        40
#define NUMBER                          41
#define LIST                            42
#define NULLTOK                         43
#define NOT                             44
#define WITHIN                          45
#define TO                              46
#define TRUE                            47
#define FALSE                           48
#define LSPAR                           49
#define RSPAR                           50
#define COMMA                           51
