#define AMPERSAND                        1
#define PLUS                             2
#define MINUS                            3
#define TIMES                            4
#define DIVIDE                           5
#define POWER                            6
#define WRITE                            7
#define SEMICOLON                        8
#define IDENTIFIER                       9
#define ASSIGN                          10
#define LPAR                            11
#define RPAR                            12
#define NUMTOKEN                        13
#define STRTOKEN                        14
#define NULLTOK                         15
#define TRUE                            16
#define FALSE                           17
