/* This file is automatically generated by Lemon from input grammar
** source file "grammar.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include "cjson.h"
#include "grammar.h"
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <setjmp.h>

/** start: what should be the header file */
#define DEBUG
#ifdef DEBUG
#define DEBUG_PRINT(fmt, ...) \
    fprintf(stderr, "[DEBUG] %s:%d:%s(): " fmt "\n", \
            __FILE__, __LINE__, __func__, ##__VA_ARGS__)
#else
#define DEBUG_PRINT(fmt, ...) \
    do { } while (0)
#endif

typedef struct { cJSON *cjson_ptr; } State;
typedef struct {char *value; int line;} token;

int get_token_id (char*);
const char *getValue (cJSON *token);
const char *getLine (cJSON *token);
cJSON *unary (char *fname, cJSON *a);
cJSON *binary (char *fname, cJSON *a, cJSON *b);
cJSON *ternary (char *fname, cJSON *a, cJSON *b, cJSON *c);
/** end: what should be the header file */

char *linenumber;
char *curtoken;
char *curtype;
static jmp_buf s_jumpBuffer;
#line 64 "grammar.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef TIME
#define TIME                            1
#define UPPERCASE                       2
#define AVERAGE                         3
#define INCREASE                        4
#define MAXIMUM                         5
#define IS                              6
#define AMPERSAND                       7
#define PLUS                            8
#define MINUS                           9
#define TIMES                          10
#define DIVIDE                         11
#define POWER                          12
#define UNMINUS                        13
#define RANGE                          14
#define WRITE                          15
#define SEMICOLON                      16
#define TRACE                          17
#define IDENTIFIER                     18
#define ASSIGN                         19
#define IF                             20
#define THEN                           21
#define ENDIF                          22
#define ELSE                           23
#define ELSEIF                         24
#define FOR                            25
#define IN                             26
#define DO                             27
#define ENDDO                          28
#define NOW                            29
#define CURRENTTIME                    30
#define LPAR                           31
#define RPAR                           32
#define NUMTOKEN                       33
#define TIMETOKEN                      34
#define STRTOKEN                       35
#define NUMBERTYPE                     36
#define LISTTYPE                       37
#define NULLTOK                        38
#define TRUE                           39
#define FALSE                          40
#define LSPAR                          41
#define RSPAR                          42
#define COMMA                          43
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 51
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE cJSON *
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  State *state ;
#define ParseARG_PDECL , State *state 
#define ParseARG_PARAM ,state 
#define ParseARG_FETCH  State *state =yypParser->state ;
#define ParseARG_STORE yypParser->state =state ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             62
#define YYNRULE              43
#define YYNRULE_WITH_ACTION  43
#define YYNTOKEN             44
#define YY_MAX_SHIFT         61
#define YY_MIN_SHIFTREDUCE   89
#define YY_MAX_SHIFTREDUCE   131
#define YY_ERROR_ACTION      132
#define YY_ACCEPT_ACTION     133
#define YY_NO_ACTION         134
#define YY_MIN_REDUCE        135
#define YY_MAX_REDUCE        177
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (226)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    31,   20,   18,   14,   12,   16,  133,   27,   32,   10,
 /*    10 */    34,   48,   23,   19,   17,   15,   13,   11,  108,   21,
 /*    20 */    20,   18,   14,   12,   16,   33,  145,   35,   10,  102,
 /*    30 */   103,   22,   28,  105,  106,  107,   38,  108,  125,  126,
 /*    40 */   127,    1,  128,   15,   13,   11,   61,   21,  102,  103,
 /*    50 */    22,   54,  105,  106,  107,   33,  141,  125,  126,  127,
 /*    60 */     1,  115,  116,  117,   51,   24,  137,    8,   60,  142,
 /*    70 */     3,   40,   59,   29,    2,   57,   50,   48,   23,   19,
 /*    80 */    17,   15,   13,   11,   41,   21,   49,  101,   48,   23,
 /*    90 */    19,   17,   15,   13,   11,   11,   21,   21,   19,   17,
 /*   100 */    15,   13,   11,   30,   21,   39,  129,    9,   52,   42,
 /*   110 */    48,   23,   19,   17,   15,   13,   11,   47,   21,   43,
 /*   120 */    94,   48,   23,   19,   17,   15,   13,   11,   46,   21,
 /*   130 */   137,   93,   48,   23,   19,   17,   15,   13,   11,   44,
 /*   140 */    21,   48,   23,   19,   17,   15,   13,   11,  165,   21,
 /*   150 */    36,   92,   45,   37,   25,   26,    4,    5,  104,   53,
 /*   160 */   100,   56,    6,   98,   97,   48,   23,   19,   17,   15,
 /*   170 */    13,   11,   54,   21,    7,   21,  134,  134,  134,  134,
 /*   180 */   134,  134,  134,  134,  134,  134,   24,  134,    8,   60,
 /*   190 */    54,    3,  134,  134,  134,  134,   57,  134,  134,   55,
 /*   200 */   135,   54,  134,  134,   24,  134,    8,   60,  134,    3,
 /*   210 */   134,   58,  134,  134,   57,   24,  134,    8,   60,  134,
 /*   220 */     3,  134,  134,  134,  134,   57,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    47,    1,    2,    3,    4,    5,   44,   45,   47,    9,
 /*    10 */    47,    6,    7,    8,    9,   10,   11,   12,   18,   14,
 /*    20 */     1,    2,    3,    4,    5,   47,   48,   47,    9,   29,
 /*    30 */    30,   31,   27,   33,   34,   35,   47,   18,   38,   39,
 /*    40 */    40,   41,   42,   10,   11,   12,   47,   14,   29,   30,
 /*    50 */    31,    1,   33,   34,   35,   47,   48,   38,   39,   40,
 /*    60 */    41,   36,   37,   38,   47,   15,   46,   17,   18,   49,
 /*    70 */    20,   47,   22,   23,   24,   25,   47,    6,    7,    8,
 /*    80 */     9,   10,   11,   12,   47,   14,   47,   16,    6,    7,
 /*    90 */     8,    9,   10,   11,   12,   12,   14,   14,    8,    9,
 /*   100 */    10,   11,   12,   21,   14,   47,   42,   43,   50,   47,
 /*   110 */     6,    7,    8,    9,   10,   11,   12,   47,   14,   47,
 /*   120 */    16,    6,    7,    8,    9,   10,   11,   12,   47,   14,
 /*   130 */    46,   16,    6,    7,    8,    9,   10,   11,   12,   47,
 /*   140 */    14,    6,    7,    8,    9,   10,   11,   12,   47,   14,
 /*   150 */    47,   16,   47,   47,   45,   45,   45,   19,   32,   18,
 /*   160 */    16,   18,   26,   16,   16,    6,    7,    8,    9,   10,
 /*   170 */    11,   12,    1,   14,   19,   14,   51,   51,   51,   51,
 /*   180 */    51,   51,   51,   51,   51,   51,   15,   51,   17,   18,
 /*   190 */     1,   20,   51,   51,   51,   51,   25,   51,   51,   28,
 /*   200 */     0,    1,   51,   51,   15,   51,   17,   18,   51,   20,
 /*   210 */    51,   22,   51,   51,   25,   15,   51,   17,   18,   51,
 /*   220 */    20,   51,   51,   51,   51,   25,   51,   51,   51,   51,
 /*   230 */    51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
 /*   240 */    51,   51,   51,   51,   51,   44,   44,   44,   44,   44,
 /*   250 */    44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
 /*   260 */    44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
};
#define YY_SHIFT_COUNT    (61)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (200)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   226,    0,   19,   19,   50,   19,   19,   19,   19,   19,
 /*    10 */    19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
 /*    20 */    19,   19,   19,   19,   19,  171,  189,  200,  226,  226,
 /*    30 */   226,   71,    5,   82,  104,  115,  126,  135,  159,  159,
 /*    40 */   159,  159,  159,  159,  159,   90,   33,   33,   25,   83,
 /*    50 */    83,   83,   64,  138,  141,  144,  136,  143,  147,  148,
 /*    60 */   155,  161,
};
#define YY_REDUCE_COUNT (30)
#define YY_REDUCE_MIN   (-47)
#define YY_REDUCE_MAX   (111)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -38,   58,  -22,    8,   20,  -47,  -39,  -37,  -20,  -11,
 /*    10 */    -1,   17,   24,   29,   37,   39,   62,   70,   72,   81,
 /*    20 */    92,  101,  103,  105,  106,   84,   84,   84,  109,  110,
 /*    30 */   111,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   136,  132,  132,  132,  132,  132,  132,  132,  132,  132,
 /*    10 */   132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
 /*    20 */   132,  132,  132,  132,  132,  132,  132,  132,  136,  136,
 /*    30 */   136,  132,  132,  132,  132,  132,  132,  132,  177,  176,
 /*    40 */   159,  158,  157,  156,  155,  164,  166,  167,  132,  168,
 /*    50 */   169,  170,  132,  132,  132,  132,  132,  132,  132,  132,
 /*    60 */   132,  160,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "TIME",
  /*    2 */ "UPPERCASE",
  /*    3 */ "AVERAGE",
  /*    4 */ "INCREASE",
  /*    5 */ "MAXIMUM",
  /*    6 */ "IS",
  /*    7 */ "AMPERSAND",
  /*    8 */ "PLUS",
  /*    9 */ "MINUS",
  /*   10 */ "TIMES",
  /*   11 */ "DIVIDE",
  /*   12 */ "POWER",
  /*   13 */ "UNMINUS",
  /*   14 */ "RANGE",
  /*   15 */ "WRITE",
  /*   16 */ "SEMICOLON",
  /*   17 */ "TRACE",
  /*   18 */ "IDENTIFIER",
  /*   19 */ "ASSIGN",
  /*   20 */ "IF",
  /*   21 */ "THEN",
  /*   22 */ "ENDIF",
  /*   23 */ "ELSE",
  /*   24 */ "ELSEIF",
  /*   25 */ "FOR",
  /*   26 */ "IN",
  /*   27 */ "DO",
  /*   28 */ "ENDDO",
  /*   29 */ "NOW",
  /*   30 */ "CURRENTTIME",
  /*   31 */ "LPAR",
  /*   32 */ "RPAR",
  /*   33 */ "NUMTOKEN",
  /*   34 */ "TIMETOKEN",
  /*   35 */ "STRTOKEN",
  /*   36 */ "NUMBERTYPE",
  /*   37 */ "LISTTYPE",
  /*   38 */ "NULLTOK",
  /*   39 */ "TRUE",
  /*   40 */ "FALSE",
  /*   41 */ "LSPAR",
  /*   42 */ "RSPAR",
  /*   43 */ "COMMA",
  /*   44 */ "code",
  /*   45 */ "statementblock",
  /*   46 */ "statement",
  /*   47 */ "ex",
  /*   48 */ "if_then_else",
  /*   49 */ "elseif",
  /*   50 */ "exlist",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "code ::= statementblock",
 /*   1 */ "statementblock ::=",
 /*   2 */ "statementblock ::= statementblock statement",
 /*   3 */ "statement ::= WRITE ex SEMICOLON",
 /*   4 */ "statement ::= TRACE ex SEMICOLON",
 /*   5 */ "statement ::= IDENTIFIER ASSIGN ex SEMICOLON",
 /*   6 */ "statement ::= IF if_then_else",
 /*   7 */ "if_then_else ::= ex THEN statementblock elseif",
 /*   8 */ "elseif ::= ENDIF SEMICOLON",
 /*   9 */ "elseif ::= ELSE statementblock ENDIF SEMICOLON",
 /*  10 */ "elseif ::= ELSEIF if_then_else",
 /*  11 */ "statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON",
 /*  12 */ "statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON",
 /*  13 */ "ex ::= NOW",
 /*  14 */ "ex ::= CURRENTTIME",
 /*  15 */ "ex ::= LPAR ex RPAR",
 /*  16 */ "ex ::= NUMTOKEN",
 /*  17 */ "ex ::= TIMETOKEN",
 /*  18 */ "ex ::= STRTOKEN",
 /*  19 */ "ex ::= IDENTIFIER",
 /*  20 */ "ex ::= TIME ex",
 /*  21 */ "ex ::= UPPERCASE ex",
 /*  22 */ "ex ::= MAXIMUM ex",
 /*  23 */ "ex ::= AVERAGE ex",
 /*  24 */ "ex ::= INCREASE ex",
 /*  25 */ "ex ::= MINUS ex",
 /*  26 */ "ex ::= ex IS NUMBERTYPE",
 /*  27 */ "ex ::= ex IS LISTTYPE",
 /*  28 */ "ex ::= ex IS NULLTOK",
 /*  29 */ "ex ::= ex AMPERSAND ex",
 /*  30 */ "ex ::= ex RANGE ex",
 /*  31 */ "ex ::= ex PLUS ex",
 /*  32 */ "ex ::= ex MINUS ex",
 /*  33 */ "ex ::= ex TIMES ex",
 /*  34 */ "ex ::= ex DIVIDE ex",
 /*  35 */ "ex ::= ex POWER ex",
 /*  36 */ "ex ::= NULLTOK",
 /*  37 */ "ex ::= TRUE",
 /*  38 */ "ex ::= FALSE",
 /*  39 */ "ex ::= LSPAR RSPAR",
 /*  40 */ "ex ::= LSPAR exlist RSPAR",
 /*  41 */ "exlist ::= ex",
 /*  42 */ "exlist ::= exlist COMMA ex",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    44,  /* (0) code ::= statementblock */
    45,  /* (1) statementblock ::= */
    45,  /* (2) statementblock ::= statementblock statement */
    46,  /* (3) statement ::= WRITE ex SEMICOLON */
    46,  /* (4) statement ::= TRACE ex SEMICOLON */
    46,  /* (5) statement ::= IDENTIFIER ASSIGN ex SEMICOLON */
    46,  /* (6) statement ::= IF if_then_else */
    48,  /* (7) if_then_else ::= ex THEN statementblock elseif */
    49,  /* (8) elseif ::= ENDIF SEMICOLON */
    49,  /* (9) elseif ::= ELSE statementblock ENDIF SEMICOLON */
    49,  /* (10) elseif ::= ELSEIF if_then_else */
    46,  /* (11) statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON */
    46,  /* (12) statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON */
    47,  /* (13) ex ::= NOW */
    47,  /* (14) ex ::= CURRENTTIME */
    47,  /* (15) ex ::= LPAR ex RPAR */
    47,  /* (16) ex ::= NUMTOKEN */
    47,  /* (17) ex ::= TIMETOKEN */
    47,  /* (18) ex ::= STRTOKEN */
    47,  /* (19) ex ::= IDENTIFIER */
    47,  /* (20) ex ::= TIME ex */
    47,  /* (21) ex ::= UPPERCASE ex */
    47,  /* (22) ex ::= MAXIMUM ex */
    47,  /* (23) ex ::= AVERAGE ex */
    47,  /* (24) ex ::= INCREASE ex */
    47,  /* (25) ex ::= MINUS ex */
    47,  /* (26) ex ::= ex IS NUMBERTYPE */
    47,  /* (27) ex ::= ex IS LISTTYPE */
    47,  /* (28) ex ::= ex IS NULLTOK */
    47,  /* (29) ex ::= ex AMPERSAND ex */
    47,  /* (30) ex ::= ex RANGE ex */
    47,  /* (31) ex ::= ex PLUS ex */
    47,  /* (32) ex ::= ex MINUS ex */
    47,  /* (33) ex ::= ex TIMES ex */
    47,  /* (34) ex ::= ex DIVIDE ex */
    47,  /* (35) ex ::= ex POWER ex */
    47,  /* (36) ex ::= NULLTOK */
    47,  /* (37) ex ::= TRUE */
    47,  /* (38) ex ::= FALSE */
    47,  /* (39) ex ::= LSPAR RSPAR */
    47,  /* (40) ex ::= LSPAR exlist RSPAR */
    50,  /* (41) exlist ::= ex */
    50,  /* (42) exlist ::= exlist COMMA ex */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) code ::= statementblock */
    0,  /* (1) statementblock ::= */
   -2,  /* (2) statementblock ::= statementblock statement */
   -3,  /* (3) statement ::= WRITE ex SEMICOLON */
   -3,  /* (4) statement ::= TRACE ex SEMICOLON */
   -4,  /* (5) statement ::= IDENTIFIER ASSIGN ex SEMICOLON */
   -2,  /* (6) statement ::= IF if_then_else */
   -4,  /* (7) if_then_else ::= ex THEN statementblock elseif */
   -2,  /* (8) elseif ::= ENDIF SEMICOLON */
   -4,  /* (9) elseif ::= ELSE statementblock ENDIF SEMICOLON */
   -2,  /* (10) elseif ::= ELSEIF if_then_else */
   -8,  /* (11) statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON */
   -5,  /* (12) statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON */
   -1,  /* (13) ex ::= NOW */
   -1,  /* (14) ex ::= CURRENTTIME */
   -3,  /* (15) ex ::= LPAR ex RPAR */
   -1,  /* (16) ex ::= NUMTOKEN */
   -1,  /* (17) ex ::= TIMETOKEN */
   -1,  /* (18) ex ::= STRTOKEN */
   -1,  /* (19) ex ::= IDENTIFIER */
   -2,  /* (20) ex ::= TIME ex */
   -2,  /* (21) ex ::= UPPERCASE ex */
   -2,  /* (22) ex ::= MAXIMUM ex */
   -2,  /* (23) ex ::= AVERAGE ex */
   -2,  /* (24) ex ::= INCREASE ex */
   -2,  /* (25) ex ::= MINUS ex */
   -3,  /* (26) ex ::= ex IS NUMBERTYPE */
   -3,  /* (27) ex ::= ex IS LISTTYPE */
   -3,  /* (28) ex ::= ex IS NULLTOK */
   -3,  /* (29) ex ::= ex AMPERSAND ex */
   -3,  /* (30) ex ::= ex RANGE ex */
   -3,  /* (31) ex ::= ex PLUS ex */
   -3,  /* (32) ex ::= ex MINUS ex */
   -3,  /* (33) ex ::= ex TIMES ex */
   -3,  /* (34) ex ::= ex DIVIDE ex */
   -3,  /* (35) ex ::= ex POWER ex */
   -1,  /* (36) ex ::= NULLTOK */
   -1,  /* (37) ex ::= TRUE */
   -1,  /* (38) ex ::= FALSE */
   -2,  /* (39) ex ::= LSPAR RSPAR */
   -3,  /* (40) ex ::= LSPAR exlist RSPAR */
   -1,  /* (41) exlist ::= ex */
   -3,  /* (42) exlist ::= exlist COMMA ex */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* code ::= statementblock */
#line 247 "grammar.y"
{
    state->cjson_ptr = yymsp[0].minor.yy0;
}
#line 1138 "grammar.c"
        break;
      case 1: /* statementblock ::= */
#line 256 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "STATEMENTBLOCK");
	cJSON *arg = cJSON_CreateArray();
	cJSON_AddItemToObject(res, "statements", arg);
	yymsp[1].minor.yy0 = res;
}
#line 1149 "grammar.c"
        break;
      case 2: /* statementblock ::= statementblock statement */
#line 265 "grammar.y"
{
	cJSON_AddItemToArray(cJSON_GetObjectItem ( yymsp[-1].minor.yy0, "statements"), yymsp[0].minor.yy0);
	yylhsminor.yy0 = yymsp[-1].minor.yy0;
}
#line 1157 "grammar.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* statement ::= WRITE ex SEMICOLON */
#line 275 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "WRITE");
	cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
	yymsp[-2].minor.yy0 = res;
}
#line 1168 "grammar.c"
        break;
      case 4: /* statement ::= TRACE ex SEMICOLON */
#line 283 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "TRACE");
    cJSON_AddStringToObject(res, "line", getLine(yymsp[-2].minor.yy0));
    cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
    yylhsminor.yy0 = res;
}
#line 1179 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 5: /* statement ::= IDENTIFIER ASSIGN ex SEMICOLON */
#line 296 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "ASSIGN");
	cJSON_AddStringToObject(res, "ident", getValue(yymsp[-3].minor.yy0));
	cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
	yylhsminor.yy0 = res;
}
#line 1191 "grammar.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 6: /* statement ::= IF if_then_else */
      case 10: /* elseif ::= ELSEIF if_then_else */ yytestcase(yyruleno==10);
#line 306 "grammar.y"
{yymsp[-1].minor.yy0 = yymsp[0].minor.yy0;}
#line 1198 "grammar.c"
        break;
      case 7: /* if_then_else ::= ex THEN statementblock elseif */
#line 309 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "IF");
    cJSON_AddItemToObject(res, "condition", yymsp[-3].minor.yy0);
    cJSON_AddItemToObject(res, "thenbranch", (yymsp[-1].minor.yy0));
    cJSON_AddItemToObject(res, "elsebranch", (yymsp[0].minor.yy0));
    yylhsminor.yy0 = res;
}
#line 1210 "grammar.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 8: /* elseif ::= ENDIF SEMICOLON */
#line 320 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "STATEMENTBLOCK");
    cJSON *arg = cJSON_CreateArray();
    cJSON_AddItemToObject(res, "statements", arg);
    yymsp[-1].minor.yy0 = res;
}
#line 1222 "grammar.c"
        break;
      case 9: /* elseif ::= ELSE statementblock ENDIF SEMICOLON */
#line 329 "grammar.y"
{yymsp[-3].minor.yy0 = yymsp[-2].minor.yy0;}
#line 1227 "grammar.c"
        break;
      case 11: /* statement ::= FOR IDENTIFIER IN ex DO statementblock ENDDO SEMICOLON */
#line 336 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "FOR");
    cJSON_AddStringToObject(res, "varname", getValue(yymsp[-6].minor.yy0));
    cJSON_AddItemToObject(res, "expression", yymsp[-4].minor.yy0);
    cJSON_AddItemToObject(res, "statements", yymsp[-2].minor.yy0);
    yymsp[-7].minor.yy0 = res;
}
#line 1239 "grammar.c"
        break;
      case 12: /* statement ::= TIME IDENTIFIER ASSIGN ex SEMICOLON */
#line 347 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "TIMEASSIGN");
	cJSON_AddStringToObject(res, "ident", getValue(yymsp[-3].minor.yy0));
	cJSON_AddItemToObject(res, "arg", yymsp[-1].minor.yy0);
	yymsp[-4].minor.yy0 = res;
}
#line 1250 "grammar.c"
        break;
      case 13: /* ex ::= NOW */
#line 356 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "NOW");
	yymsp[0].minor.yy0 = res;
}
#line 1259 "grammar.c"
        break;
      case 14: /* ex ::= CURRENTTIME */
#line 363 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "CURRENTTIME");
	yymsp[0].minor.yy0 = res;
}
#line 1268 "grammar.c"
        break;
      case 15: /* ex ::= LPAR ex RPAR */
#line 370 "grammar.y"
{
	yymsp[-2].minor.yy0 = yymsp[-1].minor.yy0;
}
#line 1275 "grammar.c"
        break;
      case 16: /* ex ::= NUMTOKEN */
#line 376 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "NUMTOKEN");
	cJSON_AddStringToObject(res, "value", getValue(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1285 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 17: /* ex ::= TIMETOKEN */
#line 384 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "TIMETOKEN");
	cJSON_AddStringToObject(res, "value", getValue(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1296 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 18: /* ex ::= STRTOKEN */
#line 393 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "STRTOKEN");
	cJSON_AddStringToObject(res, "value", getValue(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1307 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 19: /* ex ::= IDENTIFIER */
#line 402 "grammar.y"
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", "VARIABLE");
	cJSON_AddStringToObject(res, "name", getValue(yymsp[0].minor.yy0));
	cJSON_AddStringToObject(res, "line", getLine(yymsp[0].minor.yy0));
	yylhsminor.yy0 = res;
}
#line 1319 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 20: /* ex ::= TIME ex */
#line 411 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("TIME", yymsp[0].minor.yy0); }
#line 1325 "grammar.c"
        break;
      case 21: /* ex ::= UPPERCASE ex */
#line 414 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("UPPERCASE", yymsp[0].minor.yy0); }
#line 1330 "grammar.c"
        break;
      case 22: /* ex ::= MAXIMUM ex */
#line 417 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("MAXIMUM", yymsp[0].minor.yy0); }
#line 1335 "grammar.c"
        break;
      case 23: /* ex ::= AVERAGE ex */
#line 420 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("AVERAGE", yymsp[0].minor.yy0); }
#line 1340 "grammar.c"
        break;
      case 24: /* ex ::= INCREASE ex */
#line 423 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("INCREASE", yymsp[0].minor.yy0); }
#line 1345 "grammar.c"
        break;
      case 25: /* ex ::= MINUS ex */
#line 426 "grammar.y"
{ yymsp[-1].minor.yy0 = unary("UNMINUS", yymsp[0].minor.yy0); }
#line 1350 "grammar.c"
        break;
      case 26: /* ex ::= ex IS NUMBERTYPE */
#line 429 "grammar.y"
{ yylhsminor.yy0 = unary("ISNUMBER", yymsp[-2].minor.yy0); }
#line 1355 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 27: /* ex ::= ex IS LISTTYPE */
#line 432 "grammar.y"
{ yylhsminor.yy0 = unary("ISLIST", yymsp[-2].minor.yy0); }
#line 1361 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 28: /* ex ::= ex IS NULLTOK */
#line 435 "grammar.y"
{ yylhsminor.yy0 = unary("ISNULL", yymsp[-2].minor.yy0); }
#line 1367 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 29: /* ex ::= ex AMPERSAND ex */
#line 438 "grammar.y"
{yylhsminor.yy0 = binary ("AMPERSAND", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1373 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 30: /* ex ::= ex RANGE ex */
#line 441 "grammar.y"
{yylhsminor.yy0 = binary ("RANGE", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1379 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 31: /* ex ::= ex PLUS ex */
#line 444 "grammar.y"
{yylhsminor.yy0 = binary ("PLUS", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1385 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 32: /* ex ::= ex MINUS ex */
#line 447 "grammar.y"
{yylhsminor.yy0 = binary ("MINUS", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1391 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 33: /* ex ::= ex TIMES ex */
#line 450 "grammar.y"
{yylhsminor.yy0 = binary ("TIMES", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1397 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 34: /* ex ::= ex DIVIDE ex */
#line 453 "grammar.y"
{yylhsminor.yy0 = binary ("DIVIDE", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1403 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 35: /* ex ::= ex POWER ex */
#line 456 "grammar.y"
{yylhsminor.yy0 = binary ("POWER", yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1409 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 36: /* ex ::= NULLTOK */
#line 459 "grammar.y"
{
cJSON *res = cJSON_CreateObject();
cJSON_AddStringToObject(res, "type", "NULL");
yymsp[0].minor.yy0 = res;
}
#line 1419 "grammar.c"
        break;
      case 37: /* ex ::= TRUE */
#line 466 "grammar.y"
{
 	cJSON *res = cJSON_CreateObject();
 	cJSON_AddStringToObject(res, "type", "TRUE");
 	yymsp[0].minor.yy0 = res;
}
#line 1428 "grammar.c"
        break;
      case 38: /* ex ::= FALSE */
#line 473 "grammar.y"
{
 	cJSON *res = cJSON_CreateObject();
 	cJSON_AddStringToObject(res, "type", "FALSE");
 	yymsp[0].minor.yy0 = res;
}
#line 1437 "grammar.c"
        break;
      case 39: /* ex ::= LSPAR RSPAR */
#line 480 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "EMPTYLIST");
    yymsp[-1].minor.yy0 = res;
}
#line 1446 "grammar.c"
        break;
      case 40: /* ex ::= LSPAR exlist RSPAR */
#line 488 "grammar.y"
{
    cJSON *res = cJSON_CreateObject();
    cJSON_AddStringToObject(res, "type", "LIST");
    cJSON_AddItemToObject(res, "items", yymsp[-1].minor.yy0);
    yymsp[-2].minor.yy0 = res;
}
#line 1456 "grammar.c"
        break;
      case 41: /* exlist ::= ex */
#line 496 "grammar.y"
{
    cJSON *arg = cJSON_CreateArray();
    cJSON_AddItemToArray(arg, yymsp[0].minor.yy0);
    yylhsminor.yy0 = arg;
}
#line 1465 "grammar.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 42: /* exlist ::= exlist COMMA ex */
#line 503 "grammar.y"
{
    cJSON_AddItemToArray(yymsp[-2].minor.yy0,yymsp[0].minor.yy0);
    yylhsminor.yy0 = yymsp[-2].minor.yy0;
}
#line 1474 "grammar.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 219 "grammar.y"

    longjmp(s_jumpBuffer, 1);
#line 1540 "grammar.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
#line 39 "grammar.y"


token* create_token (char *value, int line) {
	token *t = (token*) malloc (sizeof (token));
	t->value = strdup (value);
	t->line = line;
	return t;
}

const char * getValue (cJSON* token) {
	return cJSON_GetObjectItem (token, "value")->valuestring;
}


const char * getLine (cJSON* token) {
	return cJSON_GetObjectItem (token, "line")->valuestring;
}


const char *parse_to_string(const char *input) {
	int jmp_val = setjmp(s_jumpBuffer);
	if (jmp_val != 0) {
        size_t buf_size = 256;
        char buf[buf_size];
        int n;
        if (jmp_val == 1) {
            n = snprintf(
            buf,
            buf_size,
            "{\"error\" : true, \"message\": \"Syntax Error: Compiler reports unexpected token \\\"%s\\\" of type \\\"%s\\\" in line %s\"}\n",
            curtoken, curtype, linenumber
        );
        } else if (jmp_val == 2) {
        	n = snprintf (buf, buf_size, "{\"error\" : true, \"message\": \"UNKNOWN TOKEN TYPE %s\"}\n", curtoken);
        } else {
        	n = snprintf (buf, buf_size, "{\"error\" : true, \"message\": \"Jumped here dont know why...!\"}\n");
        }

        // allocate n+1 chars (for the null terminator)
        char *res = malloc(n + 1);
        if (res == NULL) exit(1);

        // copy exactly n chars + '\0'
        memcpy(res, buf, n + 1);

        return res;
	} else {
	    cJSON *root = cJSON_Parse(input);
        State state;

	    if (!root) {
	    	printf("JSON invalid\n");
	    	exit(0);
	    }

	    void* pParser = ParseAlloc (malloc);
	    int num = cJSON_GetArraySize (root);

	    for (int i = 0; i < num; i++ ) {

	    	// Knoten im Token-Stream auslesen
	    	cJSON *node = cJSON_GetArrayItem(root,i);

	    	char *line = cJSON_GetArrayItem(node,0)->valuestring;
	    	char *type = cJSON_GetArrayItem(node,1)->valuestring;
	    	char *value = cJSON_GetArrayItem(node,2)->valuestring;

	    	cJSON *tok = cJSON_CreateObject();
	    	cJSON_AddStringToObject(tok, "value", value);
	    	cJSON_AddStringToObject(tok, "line", line);

	    	linenumber = line;
	    	curtoken = value;
	    	curtype = type;
	    	// THE und Kommentare werden ueberlesen
	    	if (strcmp(type, "THE") == 0) continue;
	    	if (strcmp(type, "COMMENT") == 0) continue;
	    	if (strcmp(type, "MCOMMENT") == 0) continue;

	    	int tokenid = get_token_id (type);
	    	Parse (pParser, tokenid, tok, &state);

	    }
	    Parse (pParser, 0, 0, &state);
        ParseFree(pParser, free );
        return cJSON_Print(state.cjson_ptr);
	}
}




///////////////////////
///////////////////////
// TOKENS
///////////////////////
///////////////////////

int get_token_id (char *token) {
	if (strcmp(token, "AMPERSAND") == 0) return AMPERSAND;
	if (strcmp(token, "ASSIGN") == 0) return ASSIGN;
	if (strcmp(token, "COMMA") == 0) return COMMA;
	if (strcmp(token, "DIVIDE") == 0) return DIVIDE;
	if (strcmp(token, "IDENTIFIER") == 0) return IDENTIFIER;
	// if (strcmp(token, "LISTTYPE") == 0) return LISTTYPE;
	if (strcmp(token, "LPAR") == 0) return LPAR;
	if (strcmp(token, "LSPAR") == 0) return LSPAR;
	if (strcmp(token, "MINUS") == 0) return MINUS;
	if (strcmp(token, "NULL") == 0) return NULLTOK;
	if (strcmp(token, "NUMTOKEN") == 0) return NUMTOKEN;
	if (strcmp(token, "NUMBERTYPE") == 0) return NUMBERTYPE;
	if (strcmp(token, "PLUS") == 0) return PLUS;
	if (strcmp(token, "POWER") == 0) return POWER;
	if (strcmp(token, "RPAR") == 0) return RPAR;
	if (strcmp(token, "RSPAR") == 0) return RSPAR;
	if (strcmp(token, "SEMICOLON") == 0) return SEMICOLON;
	if (strcmp(token, "STRTOKEN") == 0) return STRTOKEN;
	if (strcmp(token, "TIME") == 0) return TIME;
	if (strcmp(token, "TIMES") == 0) return TIMES;
	if (strcmp(token, "TIMETOKEN") == 0) return TIMETOKEN;
	if (strcmp(token, "TRACE") == 0) return TRACE;
	if (strcmp(token, "WRITE") == 0) return WRITE;
 	if (strcmp(token, "AVERAGE") == 0) return AVERAGE;
 	if (strcmp(token, "CURRENTTIME") == 0) return CURRENTTIME;
 	if (strcmp(token, "DO") == 0) return DO;
 	if (strcmp(token, "ELSE") == 0) return ELSE;
 	if (strcmp(token, "ENDDO") == 0) return ENDDO;
 	if (strcmp(token, "ENDIF") == 0) return ENDIF;
 	if (strcmp(token, "FALSE") == 0) return FALSE;
 	if (strcmp(token, "FOR") == 0) return FOR;
 	if (strcmp(token, "IF") == 0) return IF;
 	if (strcmp(token, "IN") == 0) return IN;
 	if (strcmp(token, "INCREASE") == 0) return INCREASE;
 	if (strcmp(token, "MAXIMUM") == 0) return MAXIMUM;
 	if (strcmp(token, "NOW") == 0) return NOW;
 	if (strcmp(token, "RANGE") == 0) return RANGE;
 	if (strcmp(token, "THEN") == 0) return THEN;
 	if (strcmp(token, "TRUE") == 0) return TRUE;
 	if (strcmp(token, "UPPERCASE") == 0) return UPPERCASE;
    curtoken = token;
    longjmp(s_jumpBuffer, 2);
}



cJSON* unary (char* fname, cJSON* a)
{
	cJSON *res = cJSON_CreateObject();
	cJSON_AddStringToObject(res, "type", fname);
	cJSON_AddItemToObject(res, "arg", a);
	return res;
}



cJSON* binary (char *fname, cJSON *a, cJSON *b)
{
	cJSON *res = cJSON_CreateObject();
	cJSON *arg = cJSON_CreateArray();
	cJSON_AddItemToArray(arg, a);
	cJSON_AddItemToArray(arg, b);
	cJSON_AddStringToObject(res, "type", fname);
	cJSON_AddItemToObject(res, "arg", arg);
	return res;
}

cJSON* ternary (char *fname, cJSON *a, cJSON *b, cJSON *c)
{
	cJSON *res = cJSON_CreateObject();
	cJSON *arg = cJSON_CreateArray();
	cJSON_AddItemToArray(arg, a);
	cJSON_AddItemToArray(arg, b);
	cJSON_AddItemToArray(arg, c);
	cJSON_AddStringToObject(res, "type", fname);
	cJSON_AddItemToObject(res, "arg", arg);
	return res;
}

#line 1988 "grammar.c"
